Repository TeamWeatherMood/WeatherMood, pull requests merged in 2021-07, with the labels that each got.

#2 처음 프로젝트 세팅입니다.
  .gitignore
  WeatherMood.xcodeproj/project.pbxproj
  WeatherMood.xcodeproj/xcshareddata/xcschemes/WeatherMood.xcscheme
  WeatherMood.xcodeproj/xcshareddata/xcschemes/WeatherMoodTest.xcscheme
  WeatherMood/CoreData/WeatherMood.xcdatamodeld/.xccurrentversion
  WeatherMood/CoreData/WeatherMood.xcdatamodeld/WeatherMood.xcdatamodel/contents
  WeatherMood/SupportingFiles/AppDelegate.swift
  WeatherMood/SupportingFiles/Assets.xcassets/.DS_Store
  WeatherMood/SupportingFiles/Assets.xcassets/AccentColor.colorset/Contents.json
  WeatherMood/SupportingFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
  WeatherMood/SupportingFiles/Assets.xcassets/Contents.json
  WeatherMood/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  WeatherMood/SupportingFiles/Info.plist
  WeatherMood/SupportingFiles/SceneDelegate.swift
  WeatherMoodTests/Info.plist
  WeatherMoodTests/WeatherMoodTests.swift
Labels: Environment

#3 템플릿 추가
  .github/auto_assign.yml
  .github/pull_request_template.md
  README.md
Labels: 📝 documentation

#7 feat: Lottie 설치
  Cartfile
  Cartfile.resolved
  WeatherMood.xcodeproj/project.pbxproj
  WeatherMood/ViewController.swift
Labels: Environment

#13 베이스 코드 작성
  WeatherMood.xcodeproj/project.pbxproj
  WeatherMood/Coordinator/Coordinator.swift
  WeatherMood/Coordinator/MainCoordinator.swift
  WeatherMood/SupportingFiles/SceneDelegate.swift
  WeatherMood/View/Viewable.swift
  WeatherMood/ViewController.swift
  WeatherMood/ViewController/BaseViewController.swift
  WeatherMood/ViewController/ConfigurationViewController.swift
  WeatherMood/ViewController/DiaryCalendarViewController.swift
  WeatherMood/ViewController/DiaryContainerViewController.swift
  WeatherMood/ViewController/DiaryListViewController.swift
  WeatherMood/ViewController/MainViewController.swift
  WeatherMood/ViewController/SelectingEmoticonViewController.swift
  WeatherMood/ViewController/WritingDiaryViewController.swift
  WeatherMood/ViewModel/ConfigurationViewModel.swift
  WeatherMood/ViewModel/DiaryCalendarViewModel.swift
  WeatherMood/ViewModel/DiaryContainerViewModel.swift
  WeatherMood/ViewModel/DiaryListViewModel.swift
  WeatherMood/ViewModel/EmoticonSelectingViewModel.swift
  WeatherMood/ViewModel/MainViewModel.swift
  WeatherMood/ViewModel/ViewModelType.swift
  WeatherMood/ViewModel/WritingDiaryViewModel.swift
Labels: 🛠 feature

#15 SwiftUI Preview Extension
  WeatherMood.xcodeproj/project.pbxproj
  WeatherMood/Extension/UIView+Preview.swift
  WeatherMood/Extension/UIViewController+Preview.swift
Labels: 🛠 feature
